// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getModel
List getModel(StringVector input);
RcppExport SEXP rcat_getModel(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< StringVector >::type input(inputSEXP);
    __result = Rcpp::wrap(getModel(input));
    return __result;
END_RCPP
}
// setnrun_cat
List setnrun_cat(List input);
RcppExport SEXP rcat_setnrun_cat(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type input(inputSEXP);
    __result = Rcpp::wrap(setnrun_cat(input));
    return __result;
END_RCPP
}
// run_cat
SEXP run_cat(List params);
RcppExport SEXP rcat_run_cat(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    __result = Rcpp::wrap(run_cat(params));
    return __result;
END_RCPP
}
// rcpp_run_cat
StringVector rcpp_run_cat(CharacterVector input, CharacterVector report, CharacterVector bin);
RcppExport SEXP rcat_rcpp_run_cat(SEXP inputSEXP, SEXP reportSEXP, SEXP binSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type report(reportSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type bin(binSEXP);
    __result = Rcpp::wrap(rcpp_run_cat(input, report, bin));
    return __result;
END_RCPP
}
// read_cat_serieses
SEXP read_cat_serieses(StringVector filename);
RcppExport SEXP rcat_read_cat_serieses(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< StringVector >::type filename(filenameSEXP);
    __result = Rcpp::wrap(read_cat_serieses(filename));
    return __result;
END_RCPP
}
// write_cat_serieses
SEXP write_cat_serieses(StringVector filename, List data);
RcppExport SEXP rcat_write_cat_serieses(SEXP filenameSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< StringVector >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    __result = Rcpp::wrap(write_cat_serieses(filename, data));
    return __result;
END_RCPP
}
