// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// run_cat
List run_cat(List params);
RcppExport SEXP rcat_run_cat(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    __result = Rcpp::wrap(run_cat(params));
    return __result;
END_RCPP
}
// rcpp_run_cat
StringVector rcpp_run_cat(CharacterVector input, CharacterVector report, CharacterVector bin);
RcppExport SEXP rcat_rcpp_run_cat(SEXP inputSEXP, SEXP reportSEXP, SEXP binSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type report(reportSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type bin(binSEXP);
    __result = Rcpp::wrap(rcpp_run_cat(input, report, bin));
    return __result;
END_RCPP
}
// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP rcat_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(timesTwo(x));
    return __result;
END_RCPP
}
