# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_run_cat <- function(input, report, bin) {
    .Call('rcat_rcpp_run_cat', PACKAGE = 'rcat', input, report, bin)
}

timesTwo <- function(x) {
    .Call('rcat_timesTwo', PACKAGE = 'rcat', x)
}

